services:
  - type: web
    name: form-automator
    runtime: python
    buildCommand: pip install -r requirements.txt && PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/src/.playwright python -m playwright install chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright